#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the ASP.NET sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The ASP.NET app container
  aspnet:
    # https://hub.docker.com/_/microsoft-dotnet-sdk/
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: ${APP_CONTAINER_NAME:-aspnet_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start The .NET CLI dev server.
    # https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch
    command: ["dotnet", "watch"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-aspnet_local}"
