#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Soketi sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Soketi client app container
  client:
    # https://hub.docker.com/_/nginx
    image: nginx:alpine
    container_name: ${CLIENT_CONTAINER_NAME:-soketi_client}
    depends_on:
      - soketi
      - server
    networks:
      - local
    ports:
      - ${CLIENT_PORT:-80}:80
    # Map the app container exposed port to the host port.
    volumes:
      - .${CLIENT_DIR:-/client}:/usr/share/nginx/html

  # The Soketi server app container
  server:
    # https://hub.docker.com/_/node
    image: node:alpine
    container_name: ${SERVER_CONTAINER_NAME:-soketi_server}
    depends_on:
      - soketi
    networks:
      - local
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    tty: true
    volumes:
      - .${SERVER_DIR:-/server}:/app
    working_dir: /app
    # Start the Node.js webserver.
    # https://nodejs.org/api/cli.html#command-line-api
    command: ["npm", "run", "watch"]

  # The Soketi app container.
  soketi:
    # https://hub.docker.com/_/node
    image: node:16
    container_name: ${APP_CONTAINER_NAME:-soketi_app}
    environment:
      SOKETI_DEBUG: true
      SOKETI_METRICS_ENABLED: true
      SOKETI_METRICS_SERVER_PORT: ${METRICS_SERVER_PORT:-9601}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-6001}:6001
      - ${METRICS_SERVER_PORT:-9601}:${METRICS_SERVER_PORT:-9601}
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Wiki.js dev server.
    command: ['node', 'bin/server.js', 'start']

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-soketi_local}"
